### ISSUE TITLE
チェック洩れの局面あり？

### ISSUE THREAD

**Issue by acepck** [Nyanyan/Shortest_Draw_Othello#1]
f5f4g3e6c4b3b4g4f7g8b2a4h4c2d2d1d7e2d6a2
全部を確認していませんが、この他にも700以上の手順がありそうです。
generate_boardsからfind_pathを呼ぶときに対称形によっては初形から到達できない局面があることが原因かも。
完全に書き換えたgenerate_boardsを使って確認したので元のコードでもこれが原因か分かりませんが。

**Comment by Nyanyan** [comment]
ご報告ありがとうございます！今から確認します

**Comment by Nyanyan** [comment]
@acepck 改めて、バグ報告ありがとうございました。おっしゃるとおりfind_pathを呼ぶときのバグがありました。また、シルエット生成にもバグがありました。
バグの修正が完了し、改めて計算し直したところ、185のユニークな棋譜(初手を固定したときに別々と判定できるもの)と10個のユニークな終局結果(線対称・点対称・回転対称を同一視)が見つかりました。
700以上の手順は見つからなかったのですが、もし以下のファイルに未記載の棋譜・終局形を見つけましたらぜひご指摘いただければと思います
https://github.com/Nyanyan/Shortest_Draw_Othello/blob/85749145cd29978509de2bdc43de4b82a0e3d2f3/result/result_all_summarized.txt

**Comment by acepck** [comment]
734の棋譜は8つの対称形全てを作ってfind_pathを呼んだときのものでした。
差分を取ると325個の棋譜が多くありますが棋譜を変換すれば同じものだと思います。

f5f6e6f4g7c6f3g2f2f7h2f1e2h3f8h1b7a8c4d2
余分にあった棋譜のうちの一つ

[ddd.txt](https://github.com/user-attachments/files/16465188/ddd.txt)

**Comment by Nyanyan** [comment]
@acepck ご協力ありがとうございました。新しい結果でREADMEを書き直しました。
[Qiitaの記事](https://qiita.com/Nyanyan_Cube/items/ccab30af5c6a2b9d1e06)もアップデートいたします。
