### ISSUE TITLE
冗長だったかも

### ISSUE THREAD

**Issue by acepck** [Nyanyan/Shortest_Draw_Othello#4]
採用ありがとうございました

348行目などの
group |= (cell_bit >> 1) & 0x7F7F7F7F7F7F7F7FULL;
group |= (cell_bit << 1) & 0xFEFEFEFEFEFEFEFEULL;
ここら辺は左シフトだけなど全部片側だけで良かったかも知れません

それと昨日の修正で383と384行も不要なコードになっていると思います

**Comment by Nyanyan** [comment]
@acepck ありがとうございます。修正しました
